### ISSUE TITLE
SELECTOR.IN File not found or pathlength is too long

### ISSUE THREAD

**Issue by JohnStults** [AgriHarmony/HYDRUS-1-D-gfortran#2]
I am trying to run this version of Hydrus on a Ubuntu 16.04 Virtualbox with gfortran installed in the box.

I get to the final command and get the attached error message from the system.  I have tried modifying the path in the LEVEL_01.dir file but still get the same error no matter how I format the path
![error](https://user-images.githubusercontent.com/26384148/63288702-95691000-c27a-11e9-8e82-151295d195ca.PNG)
.

**Comment by JohnStults** [comment]
I figured it out.  Reinstalled the system and everything works well now.  Must have been a typo or something that I missed while reading.

**Comment by ykhorzon** [comment]
OK. If you have any questions or suggestions, feel free to create issue.
